import { useEffect, useId, useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Eye, PackagePlus, Pencil, Plus, Search, Trash2, Upload, X } from 'lucide-react';
import { toast } from 'sonner';
import { api, apiError } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { UploadField } from '@/components/employees/upload-fields';
import { PageHeader } from '@/components/common/page-header';
import { ErrorState, LoadingState } from '@/components/common/states';
import { confirm } from '@/lib/confirm';
import { useLocale } from '@/store/locale';
import { getPortalPreviewTarget } from '@/lib/portal-preview-model';
import { PortalLivePreview, createPortalDraftKey, publishPortalDraft, removePortalDraft, restorePortalDraft, writePortalDraft } from '@/components/portal/portal-live-preview';

type FieldType = 'text'|'number'|'date'|'time'|'url'|'textarea'|'select'|'branch'|'employee'|'category'|'badge'|'image'|'file'|'images'|'files'|'checkbox'|'color';
type Field = { key:string; label:string; type?:FieldType; required?:boolean; options?:Array<{value:string;label:string}>; wide?:boolean };
type Config = { title:string; type:string; fields:Field[]; setting?:'company'|'about'; fixedStatus?:string; report?:boolean; noCreate?:boolean; viewOnly?:boolean; allowDelete?:boolean };
type Row = { id:number; title?:string; status:string; branchId?:number|null; data:Record<string,any>; isActive:boolean; createdAt?:string|null };
type Options = { branches:Array<{id:number;name:string|null}>; employees:Array<{id:number;name:string|null;code?:number;branchId?:number}>; categories:Array<{id:number;name:string}>; badges:Array<{id:number;name:string}>; jobs:Array<{id:number;name:string}> };
type PreviewBadge = { id:number; name:string; nameEn:string|null; type:string|null; backgroundColor:unknown; textColor:unknown };
type PreviewBadgePage = { items:Row[]; total:number; page:number; pageSize:number };
const PREVIEW_BADGE_PAGE_SIZE=100;
const MAX_PREVIEW_BADGE_PAGES=20;

const title:Field={key:'title',label:'العنوان',required:true};
const dateField:Field={key:'date',label:'التاريخ',type:'date'};
const image:Field={key:'mainImage',label:'الصورة الرئيسية',type:'image'};
const CONFIG:Record<string,Config>={
  company:{title:'بيانات البرنامج',type:'company',setting:'company',fields:[
    {key:'nameweb',label:'اسم البرنامج',required:true},{key:'abbreviation_name',label:'الاسم المختصر'},{key:'slogan',label:'الشعار النصي'},
    {key:'summary_company',label:'نبذة عن البرنامج',type:'textarea',wide:true},{key:'address',label:'العنوان',type:'textarea',wide:true},
    {key:'website',label:'الموقع الإلكتروني',type:'url'},{key:'email',label:'البريد الإلكتروني'},{key:'email_cadangan',label:'البريد الاحتياطي'},
    {key:'telepon',label:'الهاتف'},{key:'hp',label:'الجوال'},{key:'fax',label:'الفاكس'},{key:'logo',label:'الشعار',type:'image'},
    {key:'icon',label:'أيقونة الموقع',type:'image'},{key:'footer',label:'نص التذييل'},{key:'facebook',label:'Facebook',type:'url'},
    {key:'twitter',label:'X / Twitter',type:'url'},{key:'instagram',label:'Instagram',type:'url'},{key:'google_plus',label:'YouTube',type:'url'},{key:'google_map',label:'كود/رابط الخريطة',type:'textarea',wide:true},
    {key:'keywords',label:'كلمات SEO',type:'textarea',wide:true},{key:'metatext',label:'وصف SEO',type:'textarea',wide:true},
  ]},
  sliders:{title:'السلايدر',type:'sliders',fields:[title,{key:'slugTitle',label:'العنوان المختصر'},dateField,image,{key:'details',label:'التفاصيل',type:'textarea',wide:true}]},
  partners:{title:'التعاقدات',type:'partners',fields:[{...title,label:'اسم الجهة'},dateField,image,{key:'details',label:'التفاصيل',type:'textarea',wide:true}]},
  policies:{title:'السياسات واللوائح',type:'policies',fields:[title,dateField,{key:'type',label:'النوع',type:'select',options:[{value:'1',label:'سياسة'},{value:'2',label:'لائحة'}]},{key:'filePath',label:'الملف',type:'file'},{key:'details',label:'التفاصيل',type:'textarea',wide:true}]},
  about:{title:'نبذة عن الجيم',type:'about',setting:'about',fields:[title,{key:'mainImage',label:'الصورة',type:'image'},{key:'details',label:'المحتوى',type:'textarea',wide:true}]},
  photos:{title:'مكتبة الصور',type:'photos',fields:[title,{key:'branchId',label:'الفرع',type:'branch',required:true},dateField,image,{key:'images',label:'صور الألبوم',type:'images',wide:true},{key:'details',label:'التفاصيل',type:'textarea',wide:true}]},
  videos:{title:'مكتبة الفيديوهات',type:'videos',fields:[title,{key:'slugTitle',label:'العنوان المختصر'},dateField,{key:'videoLink',label:'رابط الفيديو',type:'url',required:true},image,{key:'mainPageVideo',label:'يظهر في الرئيسية',type:'checkbox'}]},
  'hero-videos':{title:'فيديوهات الرئيسية',type:'hero-videos',fields:[title,{key:'branchId',label:'الفرع',type:'branch',required:true},dateField,{key:'videoLink',label:'رابط الفيديو',type:'url',required:true},image,{key:'mainPageVideo',label:'مفعّل في الرئيسية',type:'checkbox'}]},
  branches:{title:'إعدادات الفروع',type:'branches',noCreate:true,fields:[{key:'branchId',label:'الفرع',type:'branch'},{key:'address',label:'العنوان',type:'textarea',wide:true},{key:'mob1',label:'هاتف 1'},{key:'mob2',label:'هاتف 2'},{key:'latMap',label:'خط العرض'},{key:'lngMap',label:'خط الطول'}]},
  trainers:{title:'مدربو البوابة',type:'trainers',fields:[{...title,label:'اسم المدرب'},{key:'branchId',label:'الفرع',type:'branch',required:true},{key:'jobTitle',label:'المسمى الوظيفي'},{key:'gender',label:'النوع',type:'select',options:[{value:'0',label:'الكل'},{value:'1',label:'ذكر'},{value:'2',label:'أنثى'}]},dateField,image]},
  classes:{title:'كلاسات البوابة',type:'classes',fields:[{...title,label:'اسم الكلاس'},{key:'branchId',label:'الفرع',type:'branch',required:true},{key:'classType',label:'الفئة',type:'select',options:[{value:'0',label:'الكل'},{value:'1',label:'رجال'},{value:'2',label:'سيدات'},{value:'3',label:'أطفال'}]},{key:'day',label:'اليوم',required:true},{key:'time',label:'الوقت',type:'time',required:true},dateField]},
  messages:{title:'الرسائل الواردة',type:'messages',fixedStatus:'unread',viewOnly:true,fields:[{key:'title',label:'الاسم'},{key:'email',label:'البريد'},{key:'phone',label:'الهاتف'},{key:'message',label:'الرسالة',type:'textarea',wide:true},{key:'date_add',label:'تاريخ الإرسال'}]},
  'messages-read':{title:'الرسائل المقروءة',type:'messages',fixedStatus:'read',viewOnly:true,fields:[{key:'title',label:'الاسم'},{key:'email',label:'البريد'},{key:'phone',label:'الهاتف'},{key:'message',label:'الرسالة',type:'textarea',wide:true},{key:'action_publisher_name',label:'تمت القراءة بواسطة'}]},
  jobs:{title:'إعلانات الوظائف',type:'jobs',fields:[{...title,label:'المسمى الوظيفي'},{key:'branchId',label:'الفرع',type:'branch'},{key:'specialization',label:'التخصص'},{key:'salary',label:'الراتب'},{key:'gender',label:'النوع',type:'select',options:[{value:'all',label:'الكل'},{value:'male',label:'ذكر'},{value:'female',label:'أنثى'}]},{key:'age',label:'السن'},{key:'experienceYears',label:'سنوات الخبرة'},{key:'startDate',label:'بداية الإعلان',type:'date'},{key:'endDate',label:'نهاية الإعلان',type:'date'},image,{key:'files',label:'مرفقات الإعلان',type:'files',wide:true},{key:'details',label:'التفاصيل',type:'textarea',wide:true}]},
  'job-applications':{title:'طلبات التوظيف الواردة',type:'job-applications',fixedStatus:'pending',viewOnly:true,fields:[{key:'title',label:'المتقدم'},{key:'jobTitle',label:'الوظيفة'},{key:'mobile',label:'الموبايل'},{key:'email',label:'البريد'},{key:'degree',label:'المؤهل'},{key:'skills',label:'المهارات',type:'textarea',wide:true},{key:'about_job',label:'عن الوظيفة',type:'textarea',wide:true},{key:'cv',label:'السيرة الذاتية',type:'url'},{key:'personalImage',label:'الصورة الشخصية',type:'url'}]},
  'job-applications-accepted':{title:'طلبات الوظائف المقبولة',type:'job-applications',fixedStatus:'accepted',viewOnly:true,fields:[{key:'title',label:'المتقدم'},{key:'jobTitle',label:'الوظيفة'},{key:'mobile',label:'الموبايل'},{key:'email',label:'البريد'},{key:'comment',label:'ملاحظة القرار',type:'textarea',wide:true}]},
  'job-applications-rejected':{title:'طلبات الوظائف المرفوضة',type:'job-applications',fixedStatus:'rejected',viewOnly:true,fields:[{key:'title',label:'المتقدم'},{key:'jobTitle',label:'الوظيفة'},{key:'mobile',label:'الموبايل'},{key:'email',label:'البريد'},{key:'comment',label:'سبب الرفض',type:'textarea',wide:true}]},
  badges:{title:'إعدادات الشارات',type:'badges',fields:[{...title,label:'الاسم العربي'},{key:'nameEn',label:'الاسم الإنجليزي'},{key:'badgeType',label:'نوع الشارة'},{key:'backgroundColor',label:'لون الخلفية',type:'color'},{key:'textColor',label:'لون النص',type:'color'},{key:'displayOrder',label:'ترتيب العرض',type:'number'}]},
  offers:{title:'عروض الموقع',type:'offers',fields:[{...title,label:'اسم العرض'},{key:'subtitle',label:'العنوان الفرعي'},{key:'startDate',label:'بداية العرض',type:'date'},{key:'endDate',label:'نهاية العرض',type:'date'},{key:'value',label:'قيمة العرض',type:'number'},{key:'image',label:'صورة العرض',type:'image'},{key:'details',label:'تفاصيل العرض',type:'textarea',wide:true}]},
  'captain-discounts':{title:'كودات خصم الكباتن للمتجر',type:'captain-discounts',fields:[{key:'captainId',label:'الكابتن',type:'employee',required:true},{key:'discountCode',label:'كود الخصم (يتولد تلقائيًا إذا تُرك فارغًا)'},{key:'discountRate',label:'نسبة الخصم %',type:'number',required:true}]},
  categories:{title:'إدارة الأقسام',type:'categories',fields:[{...title,label:'اسم القسم'},{key:'iconClass',label:'كلاس الأيقونة'},{key:'image',label:'صورة القسم',type:'image'},{key:'displayOrder',label:'ترتيب العرض',type:'number'}]},
  products:{title:'إدارة المنتجات',type:'products',fields:[{...title,label:'اسم المنتج'},{key:'nameEn',label:'الاسم الإنجليزي'},{key:'categoryId',label:'القسم',type:'category',required:true},{key:'price',label:'السعر',type:'number',required:true},{key:'oldPrice',label:'السعر القديم',type:'number'},{key:'currentStock',label:'الرصيد الحالي',type:'number'},{key:'selectedBadge',label:'الشارة',type:'badge'},{key:'image',label:'الصورة الرئيسية',type:'image'},{key:'images',label:'الصور الإضافية',type:'images',wide:true},{key:'shortDescription',label:'وصف مختصر',type:'textarea',wide:true},{key:'description',label:'الوصف',type:'textarea',wide:true},{key:'specifications',label:'المواصفات (JSON)',type:'textarea',wide:true},{key:'displayOrder',label:'ترتيب العرض',type:'number'},{key:'isFeatured',label:'منتج مميز',type:'checkbox'},{key:'isNew',label:'منتج جديد',type:'checkbox'}]},
  orders:{title:'طلبات الموقع',type:'orders',noCreate:true,viewOnly:true,allowDelete:true,fields:[{key:'title',label:'رقم الطلب'},{key:'fullName',label:'العميل'},{key:'phone',label:'الهاتف'},{key:'email',label:'البريد'},{key:'governorate',label:'المحافظة'},{key:'cityStreet',label:'العنوان',type:'textarea',wide:true},{key:'paymentMethod',label:'طريقة الدفع'},{key:'subtotal',label:'الإجمالي قبل الخصم'},{key:'couponCode',label:'كود الخصم'},{key:'couponDiscountAmount',label:'قيمة الخصم'},{key:'shippingCost',label:'الشحن'},{key:'total',label:'الصافي'},{key:'orderNotes',label:'ملاحظات الطلب',type:'textarea',wide:true},{key:'items',label:'بنود الطلب',type:'textarea',wide:true}]},
  customers:{title:'حسابات العملاء',type:'customers',noCreate:true,allowDelete:true,fields:[{key:'title',label:'الاسم'},{key:'accountType',label:'نوع الحساب'},{key:'memberCode',label:'كود العضو'},{key:'phone',label:'الهاتف'},{key:'email',label:'البريد'},{key:'governorate',label:'المحافظة'},{key:'cityStreet',label:'العنوان',type:'textarea',wide:true},{key:'discountRate',label:'نسبة الخصم %',type:'number'},{key:'discountStart',label:'بداية الخصم',type:'date'},{key:'discountEnd',label:'نهاية الخصم',type:'date'},{key:'discountActive',label:'تفعيل الخصم المؤقت',type:'checkbox'}]},
  stats:{title:'إحصائيات الموقع',type:'stats',fields:[{...title,label:'اسم الإحصائية'},{key:'numericValue',label:'القيمة',type:'number',required:true},{key:'suffix',label:'اللاحقة مثل + أو %'},{key:'displayOrder',label:'ترتيب العرض',type:'number'}]},
  services:{title:'خدمات الموقع',type:'services',fields:[{...title,label:'اسم الخدمة'},{key:'subtitle',label:'عنوان فرعي'},{key:'details',label:'وصف الخدمة',type:'textarea',wide:true},{key:'icon',label:'الأيقونة/الرمز'},{key:'image',label:'صورة الخدمة',type:'image'},{key:'linkText',label:'نص الرابط'},{key:'linkUrl',label:'مسار الرابط'},{key:'displayOrder',label:'ترتيب العرض',type:'number'}]},
  'class-showcase':{title:'كروت الكلاسات الرئيسية',type:'class-showcase',fields:[{...title,label:'اسم الكلاس'},{key:'subtitle',label:'وصف مختصر'},{key:'details',label:'التفاصيل',type:'textarea',wide:true},{key:'image',label:'صورة الكلاس',type:'image'},{key:'icon',label:'الرمز البديل'},{key:'linkText',label:'نص الزر'},{key:'linkUrl',label:'مسار الزر'},{key:'isFeatured',label:'كارت رئيسي',type:'checkbox'},{key:'displayOrder',label:'ترتيب العرض',type:'number'}]},
  'about-features':{title:'مميزات عن الجيم',type:'about-features',fields:[{...title,label:'الميزة'},{key:'icon',label:'الأيقونة/الرمز'},{key:'displayOrder',label:'ترتيب العرض',type:'number'}]},
  'coach-features':{title:'خطوات ومميزات المدرب',type:'coach-features',fields:[{...title,label:'عنوان الخطوة'},{key:'subtitle',label:'وصف الخطوة'},{key:'icon',label:'الأيقونة/الرمز'},{key:'displayOrder',label:'ترتيب العرض',type:'number'}]},
  'section-settings':{title:'إعدادات أقسام الموقع',type:'section-settings',fields:[{...title,label:'اسم القسم داخل الإدارة'},{key:'sectionKey',label:'القسم',type:'select',required:true,options:[{value:'hero',label:'البداية'},{value:'about',label:'عن النعماني'},{value:'products',label:'المنتجات'},{value:'offers',label:'العروض'},{value:'schedule',label:'جدول الكلاسات'},{value:'services',label:'الخدمات'},{value:'classes',label:'الكلاسات'},{value:'coaches',label:'المدربين'},{value:'videos',label:'الفيديوهات'},{value:'gallery',label:'معرض الصور'},{value:'membership',label:'العضوية'},{value:'branches',label:'الفروع'},{value:'contact',label:'التواصل'},{value:'lead',label:'طلب الاشتراك'},{value:'footer',label:'التذييل'}]},{key:'subtitle',label:'العنوان الصغير'},{key:'extraText',label:'العنوان الرئيسي'},{key:'details',label:'الوصف',type:'textarea',wide:true},{key:'image',label:'الصورة',type:'image'},{key:'linkText',label:'نص الزر'},{key:'linkUrl',label:'مسار الزر'},{key:'displayOrder',label:'ترتيب العرض',type:'number'}]},
  'captain-sales-report':{title:'تقرير مبيعات المتجر عن طريق الكباتن',type:'orders',report:true,noCreate:true,fields:[]},
};

const SECTION_SETTING_FIELD_KEYS:Record<string,Set<string>>={
  hero:new Set(['title','sectionKey','subtitle','extraText','details','image','linkText','linkUrl','displayOrder']),
  about:new Set(['title','sectionKey','subtitle','extraText','details','image','linkText','linkUrl','displayOrder']),
  products:new Set(['title','sectionKey','subtitle','extraText','details','linkText','linkUrl','displayOrder']),
  offers:new Set(['title','sectionKey','subtitle','extraText','details','displayOrder']),
  schedule:new Set(['title','sectionKey','subtitle','extraText','details','linkText','linkUrl','displayOrder']),
  services:new Set(['title','sectionKey','subtitle','extraText','details','linkText','linkUrl','displayOrder']),
  classes:new Set(['title','sectionKey','subtitle','extraText','details','displayOrder']),
  coaches:new Set(['title','sectionKey','subtitle','extraText','details','image','linkText','linkUrl','displayOrder']),
  videos:new Set(['title','sectionKey','subtitle','extraText','details','displayOrder']),
  gallery:new Set(['title','sectionKey','subtitle','extraText','details','displayOrder']),
  membership:new Set(['title','sectionKey','subtitle','extraText','details','displayOrder']),
  branches:new Set(['title','sectionKey','subtitle','extraText','details','displayOrder']),
  contact:new Set(['title','sectionKey','subtitle','extraText','details','displayOrder']),
  lead:new Set(['title','sectionKey','subtitle','extraText','linkText','displayOrder']),
  footer:new Set(['title','sectionKey','details','displayOrder']),
};
export function fieldsForSectionSetting<T extends Pick<Field,'key'>>(fields:T[],sectionKey:unknown):T[]{const allowed=SECTION_SETTING_FIELD_KEYS[String(sectionKey)]??new Set(['title','sectionKey','displayOrder']);return fields.filter(field=>allowed.has(field.key));}

const clean=(v:unknown)=>v==null?'':Array.isArray(v)?v.join('، '):typeof v==='object'?JSON.stringify(v):String(v);
export function selectPortalDraftFields(fields:Array<Pick<Field,'key'>>, source:Record<string,any>, structural:string[]=[]){const allowed=new Set([...fields.map(field=>field.key),...structural]);return Object.fromEntries([...allowed].filter(key=>source[key]!==undefined).map(key=>[key,source[key]]));}
export function createPortalSettingsPayload(fields:Array<Pick<Field,'key'>>, draft:Record<string,any>){return selectPortalDraftFields(fields,draft);}
export function createPortalRecordPayload(fields:Array<Pick<Field,'key'>>, draft:Record<string,any>){const fieldValues=selectPortalDraftFields(fields,draft);const hasBranch=fields.some(field=>field.key==='branchId');const data=Object.fromEntries(Object.entries(fieldValues).filter(([key])=>!['title','branchId','status'].includes(key)));return {title:fieldValues.title,status:draft.status??'active',branchId:hasBranch&&draft.branchId?Number(draft.branchId):null,data};}
const initialDraft=(row:Row,fields:Field[])=>selectPortalDraftFields(fields,{title:clean(row.title),status:row.status,branchId:row.branchId==null?'':String(row.branchId),...row.data},['status']);

export function PortalManagementPage(){
  const {pathname}=useLocation(); const screen=pathname.split('/').filter(Boolean).pop()??'company'; const config=CONFIG[screen]??CONFIG.company;
  return config.setting?<SettingsPage key={screen} config={config}/>:config.report?<CaptainReport key={screen} config={config}/>:<RecordsPage key={screen} config={config}/>;
}

function useOptions(){return useQuery({queryKey:['portal-options'],queryFn:async()=>(await api.get<Options>('/portal-management/options')).data});}
function previewBadge(row:Row):PreviewBadge{const data=row.data??{};return {id:row.id,name:row.title??String(data.name??''),nameEn:typeof data.nameEn==='string'?data.nameEn:null,type:typeof data.badgeType==='string'?data.badgeType:typeof data.type==='string'?data.type:null,backgroundColor:data.backgroundColor??null,textColor:data.textColor??null};}
function assertPreviewBadgePage(page:PreviewBadgePage, expectedPage:number, expectedTotal?:number, expectedPageSize?:number){if(!Array.isArray(page?.items)||!Number.isSafeInteger(page.total)||page.total<0||page.page!==expectedPage||!Number.isSafeInteger(page.pageSize)||page.pageSize<1||(expectedTotal!==undefined&&page.total!==expectedTotal)||(expectedPageSize!==undefined&&page.pageSize!==expectedPageSize))throw new Error('Invalid portal badge pagination response');const expectedItems=Math.min(page.pageSize,Math.max(0,page.total-(expectedPage-1)*page.pageSize));if(page.items.length!==expectedItems)throw new Error('Incomplete portal badge pagination response');}
export async function fetchAllPreviewBadges(fetchPage:(page:number,pageSize:number)=>Promise<PreviewBadgePage>):Promise<PreviewBadge[]>{const first=await fetchPage(1,PREVIEW_BADGE_PAGE_SIZE);assertPreviewBadgePage(first,1);const pages=Math.ceil(first.total/first.pageSize);if(pages>MAX_PREVIEW_BADGE_PAGES)throw new Error('Portal badge preview exceeds the safe pagination limit');const rows=[...first.items];for(let page=2;page<=pages;page++){const next=await fetchPage(page,PREVIEW_BADGE_PAGE_SIZE);assertPreviewBadgePage(next,page,first.total,first.pageSize);rows.push(...next.items);}if(rows.length!==first.total)throw new Error('Incomplete portal badge pagination response');return rows.filter(row=>row.isActive===true||row.status==='active').map(previewBadge);}
function usePreviewBadges(enabled:boolean){return useQuery({queryKey:['portal-preview-badges'],enabled,queryFn:()=>fetchAllPreviewBadges(async(page,pageSize)=>(await api.get<PreviewBadgePage>('/portal-management/badges',{params:{page,pageSize}})).data)});}
export function productPreviewBadgeState(selectedBadge:unknown, badges:PreviewBadge[]|undefined, isLoading:boolean, isError:boolean):'ready'|'loading'|'error'{if(selectedBadge==null||selectedBadge===''||selectedBadge==='none')return 'ready';if(badges?.some(badge=>String(badge.id)===String(selectedBadge)))return 'ready';return isLoading?'loading':'error';}

function SettingsPage({config}:{config:Config}){
  const {ui}=useLocale(); const qc=useQueryClient(); const {data={},isLoading,isError,error,refetch}=useQuery({queryKey:['portal-setting',config.setting],queryFn:async()=>(await api.get(`/portal-management/settings/${config.setting}`)).data});
  const [draft,setDraft]=useState<Record<string,any>>({}); const [restored,setRestored]=useState(false); const draftKey=createPortalDraftKey(config.type,'settings'); const baseline=selectPortalDraftFields(config.fields,data); const values=Object.keys(draft).length?selectPortalDraftFields(config.fields,{...baseline,...draft}):baseline;
  useEffect(()=>{if(!Object.keys(baseline).length||Object.keys(draft).length||typeof localStorage==='undefined')return;const restored=restorePortalDraft(localStorage,draftKey,baseline);if(restored.restored){setDraft(selectPortalDraftFields(config.fields,restored.values));setRestored(true);}},[baseline,draft,draftKey,config.fields]);
  const save=useMutation({mutationFn:()=>publishPortalDraft(typeof localStorage==='undefined'?null:localStorage,draftKey,()=>api.put(`/portal-management/settings/${config.setting}`,createPortalSettingsPayload(config.fields,values))),onSuccess:()=>{toast.success(ui('تم النشر بنجاح'));setDraft({});setRestored(false);qc.invalidateQueries({queryKey:['portal-setting',config.setting]});},onError:(e)=>toast.error(apiError(e))});
  const saveDraft=()=>{if(typeof localStorage!=='undefined')writePortalDraft(localStorage,draftKey,createPortalSettingsPayload(config.fields,values));setRestored(true);toast.success(ui('محفوظ على هذا الجهاز'));}; const discardDraft=()=>{if(typeof localStorage!=='undefined')removePortalDraft(localStorage,draftKey);setDraft(createPortalSettingsPayload(config.fields,baseline));setRestored(false);};
  if(isLoading)return <LoadingState/>;
  if(isError)return <ErrorState message={apiError(error)} onRetry={()=>void refetch()}/>;
  return <div className="space-y-6"><PageHeader title={ui(config.title)} eyebrow={ui('إدارة البوابة')}/><PortalLivePreview configType={config.type} entityId="settings" draft={values} surfaceLabel={ui(config.title)}>{<Card><CardContent className="grid gap-4 p-5 md:grid-cols-2">{restored&&<div className="md:col-span-2 rounded-md border border-primary/30 bg-muted px-3 py-2 text-sm" role="status">{ui('مسودة محفوظة على هذا الجهاز')}</div>}{config.fields.map(f=><PortalField key={f.key} field={f} value={values[f.key]} onChange={v=>setDraft(createPortalSettingsPayload(config.fields,{...values,[f.key]:v}))}/>) }<div className="flex flex-wrap justify-end gap-2 md:col-span-2"><Button type="button" variant="outline" onClick={discardDraft}>{ui('إلغاء المسودة')}</Button><Button type="button" variant="secondary" onClick={saveDraft}>{ui('حفظ كمسودة')}</Button><Button type="button" disabled={save.isPending} onClick={()=>save.mutate()}>{ui('نشر التعديلات')}</Button></div></CardContent></Card>}</PortalLivePreview></div>;
}

function RecordsPage({config}:{config:Config}){
  const {ui}=useLocale(); const qc=useQueryClient(); const optionsQuery=useOptions(); const options=optionsQuery.data; const badgePreviewQuery=usePreviewBadges(config.type==='products'); const [search,setSearch]=useState(''); const [editing,setEditing]=useState<Row|'new'|null>(null); const [draft,setDraft]=useState<Record<string,any>>({}); const [restored,setRestored]=useState(false); const [decision,setDecision]=useState<{row:Row;status:'accepted'|'rejected'}|null>(null); const [comment,setComment]=useState(''); const [stockRow,setStockRow]=useState<Row|null>(null); const [stockQty,setStockQty]=useState('');
  const badgePreviewState=productPreviewBadgeState(draft.selectedBadge,badgePreviewQuery.data,badgePreviewQuery.isLoading,badgePreviewQuery.isError); const badgePreviewGate=badgePreviewState==='ready'?undefined:{state:badgePreviewState,onRetry:()=>void badgePreviewQuery.refetch()};
  const recordFields=config.type==='section-settings'?fieldsForSectionSetting(config.fields,draft.sectionKey):config.fields;
  const params=useMemo(()=>({q:search||undefined,status:config.fixedStatus}),[search,config.fixedStatus]);
  const {data,isLoading,isError,error,refetch}=useQuery({queryKey:['portal-records',config.type,params],queryFn:async()=>(await api.get<{items:Row[];total:number}>(`/portal-management/${config.type}`,{params})).data});
  const refresh=()=>qc.invalidateQueries({queryKey:['portal-records',config.type]});
  const draftEntityId=editing==='new'?'new':editing?.id??'new'; const localDraftKey=createPortalDraftKey(config.type,draftEntityId);
  const save=useMutation({mutationFn:()=>{const body=createPortalRecordPayload(recordFields,draft);const id=editing==='new'?null:(editing as Row).id;return publishPortalDraft(typeof localStorage==='undefined'?null:localStorage,localDraftKey,()=>id?api.put(`/portal-management/${config.type}/${id}`,body):api.post(`/portal-management/${config.type}`,body));},onSuccess:()=>{toast.success(ui('تم النشر بنجاح'));setEditing(null);setRestored(false);refresh();},onError:e=>toast.error(apiError(e))});
  const status=useMutation({mutationFn:({id,value,note}:{id:number;value:string;note?:string})=>api.patch(`/portal-management/${config.type}/${id}/status`,{status:value,comment:note}),onSuccess:()=>{toast.success(ui('تم تحديث الحالة'));setDecision(null);setComment('');refresh();},onError:e=>toast.error(apiError(e))});
  const stock=useMutation({mutationFn:()=>api.post(`/portal-management/products/${stockRow!.id}/stock`,{quantity:Number(stockQty)}),onSuccess:()=>{toast.success(ui('تمت إضافة الرصيد'));setStockRow(null);setStockQty('');refresh();},onError:e=>toast.error(apiError(e))});
  const open=(row:Row|'new')=>{const baseline=selectPortalDraftFields(config.fields,row==='new'?{status:'active',displayOrder:1,currentStock:0,mainPageVideo:true}:initialDraft(row,config.fields),['status']);const key=createPortalDraftKey(config.type,row==='new'?'new':row.id);const restored=typeof localStorage==='undefined'?{values:baseline,restored:false}:restorePortalDraft(localStorage,key,baseline);setEditing(row);setDraft(selectPortalDraftFields(config.fields,restored.values,['status']));setRestored(restored.restored);};
  const remove=async(row:Row)=>{const extra=config.type==='orders'?` ${ui('سيتم إرجاع كميات بنود الطلب إلى رصيد المنتجات.')}`:'';if(await confirm({title:ui('تأكيد الحذف'),description:`${ui('هل تريد حذف')} «${row.title??row.id}»؟${extra}`})){try{await api.delete(`/portal-management/${config.type}/${row.id}`);toast.success(ui('تم الحذف بنجاح'));refresh();}catch(e){toast.error(apiError(e));}}};
  if(optionsQuery.isError)return <ErrorState message={apiError(optionsQuery.error)} onRetry={()=>void optionsQuery.refetch()}/>;
  const columns=config.fields.filter(f=>!['image','images','files','textarea','checkbox'].includes(f.type??'')).slice(0,4);
  if(isError)return <ErrorState message={apiError(error)} onRetry={()=>void refetch()}/>;
  return <div className="space-y-6"><PageHeader title={ui(config.title)} eyebrow={ui('إدارة البوابة')} actions={!config.noCreate&&!config.viewOnly?<Button onClick={()=>open('new')}><Plus className="me-2 size-4"/>{ui('إضافة جديد')}</Button>:undefined}/>
    <Card><CardHeader className="flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><CardTitle>{ui(config.title)}</CardTitle><div className="relative w-full sm:w-72"><Search className="absolute end-3 top-2.5 size-4 text-muted-foreground"/><Input aria-label={ui('بحث في السجلات')} value={search} onChange={e=>setSearch(e.target.value)} placeholder={ui('بحث...')}/></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-start">#</th>{columns.map(f=><th key={f.key} className="p-3 text-start">{ui(f.label)}</th>)}<th className="p-3">{ui('الحالة')}</th><th className="p-3">{ui('الإجراء')}</th></tr></thead><tbody>{isLoading?<tr><td colSpan={8} className="p-8 text-center">{ui('جاري التحميل...')}</td></tr>:!data?.items.length?<tr><td colSpan={8} className="p-8 text-center text-muted-foreground">{ui('لا توجد بيانات')}</td></tr>:data.items.map((row,i)=><tr key={row.id} className="border-b"><td className="p-3">{i+1}</td>{columns.map(f=><td key={f.key} className="max-w-64 truncate p-3">{displayValue(row,f,options,ui)}</td>)}<td className="p-3 text-center">{ui(statusLabel(row.status))}</td><td className="p-3"><div className="flex flex-wrap justify-center gap-1"><Button variant="ghost" size="icon" onClick={()=>open(row)} aria-label={ui(config.viewOnly?'عرض':'تعديل')}>{config.viewOnly?<Eye className="size-4"/>:<Pencil className="size-4"/>}</Button>
      {config.type==='messages'&&row.status==='unread'&&<Button variant="ghost" size="sm" onClick={()=>status.mutate({id:row.id,value:'read'})}><Check className="me-1 size-4"/>{ui('تمت القراءة')}</Button>}
      {config.type==='job-applications'&&row.status==='pending'&&<><Button variant="ghost" size="sm" onClick={()=>setDecision({row,status:'accepted'})}>{ui('قبول')}</Button><Button variant="ghost" size="sm" onClick={()=>setDecision({row,status:'rejected'})}>{ui('رفض')}</Button></>}
      {config.type==='orders'&&<Select value={row.status} onValueChange={v=>status.mutate({id:row.id,value:v})}><SelectTrigger className="h-8 w-32"><SelectValue/></SelectTrigger><SelectContent>{['pending','processing','completed','cancelled'].map(v=><SelectItem key={v} value={v}>{ui(statusLabel(v))}</SelectItem>)}</SelectContent></Select>}
      {['offers','badges','captain-discounts','customers','jobs','stats','services','class-showcase','about-features','coach-features','section-settings'].includes(config.type)&&<Button variant="ghost" size="sm" onClick={()=>status.mutate({id:row.id,value:row.isActive?'inactive':'active'})}>{ui(row.isActive?'إيقاف':'تفعيل')}</Button>}
      {config.type==='products'&&<Button variant="ghost" size="icon" onClick={()=>setStockRow(row)} aria-label={ui('إضافة رصيد')}><PackagePlus className="size-4"/></Button>}
      {(!config.viewOnly||config.allowDelete)&&config.type!=='branches'&&<Button variant="ghost" size="icon" aria-label={ui('حذف السجل')} onClick={()=>void remove(row)}><Trash2 className="size-4 text-destructive"/></Button>}</div></td></tr>)}</tbody></table></div></CardContent></Card>
    <Dialog open={editing!==null} onOpenChange={v=>!v&&setEditing(null)}><DialogContent className={getPortalPreviewTarget(config.type,draftEntityId)?"max-h-[94vh] max-w-7xl overflow-y-auto":"max-h-[90vh] max-w-3xl overflow-y-auto"}><DialogHeader><DialogTitle>{ui(config.title)}</DialogTitle></DialogHeader>{getPortalPreviewTarget(config.type,draftEntityId)?<PortalLivePreview configType={config.type} entityId={draftEntityId} draft={draft} options={{categories:options?.categories,badges:badgePreviewState==='ready'?badgePreviewQuery.data??options?.badges:undefined}} previewGate={config.type==='products'?badgePreviewGate:undefined} surfaceLabel={ui(config.title)}>{<><div className="grid gap-4 md:grid-cols-2">{restored&&<div className="md:col-span-2 rounded-md border border-primary/30 bg-muted px-3 py-2 text-sm" role="status">{ui('مسودة محفوظة على هذا الجهاز')}</div>}{recordFields.map(f=><PortalField key={f.key} field={f} value={draft[f.key]} options={options} disabled={config.viewOnly} onChange={v=>setDraft(selectPortalDraftFields(config.fields,{...draft,[f.key]:v},['status']))}/>)}</div><DialogFooter className="mt-4"><Button type="button" variant="outline" onClick={()=>{if(typeof localStorage!=='undefined')removePortalDraft(localStorage,localDraftKey);setDraft(selectPortalDraftFields(config.fields,editing==='new'?{status:'active',displayOrder:1,currentStock:0,mainPageVideo:true}:initialDraft(editing as Row,config.fields),['status']));setRestored(false);}}>{ui('إلغاء المسودة')}</Button><Button type="button" variant="secondary" onClick={()=>{if(typeof localStorage!=='undefined')writePortalDraft(localStorage,localDraftKey,selectPortalDraftFields(recordFields,draft,['status']));setRestored(true);toast.success(ui('محفوظ على هذا الجهاز'));}}>{ui('حفظ كمسودة')}</Button><Button disabled={save.isPending} onClick={()=>save.mutate()}>{ui('نشر التعديلات')}</Button></DialogFooter></>}</PortalLivePreview>:<><div className="grid gap-4 md:grid-cols-2">{config.fields.map(f=><PortalField key={f.key} field={f} value={draft[f.key]} options={options} disabled={config.viewOnly||(config.type==='customers'&&!['discountRate','discountStart','discountEnd','discountActive'].includes(f.key))||(config.type==='branches'&&f.key==='branchId')} onChange={v=>setDraft({...draft,[f.key]:v})}/>)}</div><DialogFooter>{!config.viewOnly&&<Button disabled={save.isPending} onClick={()=>save.mutate()}>{ui('حفظ')}</Button>}{config.type==='customers'&&<Button disabled={save.isPending} onClick={()=>save.mutate()}>{ui('حفظ الخصم')}</Button>}</DialogFooter></>}</DialogContent></Dialog>
    <Dialog open={decision!==null} onOpenChange={v=>!v&&setDecision(null)}><DialogContent><DialogHeader><DialogTitle>{ui(decision?.status==='accepted'?'قبول طلب التوظيف':'رفض طلب التوظيف')}</DialogTitle></DialogHeader><div><Label id="portal-field-1">{ui('ملاحظة القرار')}</Label><Textarea aria-labelledby="portal-field-1" className="mt-2" value={comment} onChange={e=>setComment(e.target.value)}/></div><DialogFooter><Button disabled={status.isPending} onClick={()=>decision&&status.mutate({id:decision.row.id,value:decision.status,note:comment})}>{ui('تأكيد')}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={stockRow!==null} onOpenChange={v=>!v&&setStockRow(null)}><DialogContent><DialogHeader><DialogTitle>{ui('إضافة رصيد إلى')} {stockRow?.title}</DialogTitle></DialogHeader><div><Label id="portal-field-2">{ui('الكمية المضافة')}</Label><Input aria-labelledby="portal-field-2" className="mt-2" type="number" min="1" value={stockQty} onChange={e=>setStockQty(e.target.value)}/></div><DialogFooter><Button disabled={stock.isPending||Number(stockQty)<=0} onClick={()=>stock.mutate()}>{ui('إضافة')}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function PortalField({field,value,onChange,options,disabled}:{field:Field;value:any;onChange:(v:any)=>void;options?:Options;disabled?:boolean}){
  const {ui}=useLocale(); const fieldId=useId(); const wide=field.wide||['textarea','images','files'].includes(field.type??''); const label=<Label htmlFor={fieldId}>{ui(field.label)}{field.required&&<span className="text-destructive"> *</span>}</Label>;
  if(field.type==='image'||field.type==='file')return <div className={wide?'md:col-span-2':''}>{label}<UploadField category={field.type==='image'?'portal-image':'portal-file'} value={clean(value)} onChange={onChange} accept={field.type==='image'?'image/*':undefined} preview={field.type==='image'} label={ui(field.type==='image'?'اختر صورة للرفع':'اختر ملفًا للرفع')}/></div>;
  if(field.type==='images'||field.type==='files')return <MultiUpload label={ui(field.label)} values={Array.isArray(value)?value:[]} image={field.type==='images'} disabled={disabled} onChange={onChange}/>;
  if(field.type==='checkbox')return <div className="flex items-center gap-2 pt-7"><Checkbox id={fieldId} checked={Boolean(value)&&value!=='0'} disabled={disabled} onCheckedChange={v=>onChange(v===true)}/>{label}</div>;
  const dynamic=field.type==='branch'?options?.branches.map(x=>({value:String(x.id),label:x.name??`${ui('فرع')} ${x.id}`})):field.type==='employee'?options?.employees.map(x=>({value:String(x.id),label:`${x.name??'—'}${x.code?` (${x.code})`:''}`})):field.type==='category'?options?.categories.map(x=>({value:String(x.id),label:x.name})):field.type==='badge'?[{value:'none',label:'بدون شارة'},...(options?.badges.map(x=>({value:String(x.id),label:x.name}))??[])]:field.options;
  if(dynamic)return <div className={wide?'md:col-span-2':''}>{label}<Select value={clean(value)||undefined} disabled={disabled} onValueChange={v=>onChange(v==='none'?'':v)}><SelectTrigger id={fieldId} aria-required={field.required} className="mt-1.5"><SelectValue placeholder={ui('اختر...')}/></SelectTrigger><SelectContent>{dynamic.map(o=><SelectItem key={o.value} value={o.value}>{field.options||o.value==='none'?ui(o.label):o.label}</SelectItem>)}</SelectContent></Select></div>;
  if(field.type==='textarea')return <div className="md:col-span-2">{label}<Textarea id={fieldId} required={field.required} className="mt-1.5 min-h-28" value={clean(value)} disabled={disabled} onChange={e=>onChange(e.target.value)}/></div>;
  return <div className={wide?'md:col-span-2':''}>{label}<Input id={fieldId} required={field.required} className="mt-1.5" type={field.type==='color'?'color':field.type??'text'} value={clean(value)} disabled={disabled} onChange={e=>onChange(e.target.value)}/></div>;
}

function MultiUpload({label,values,onChange,image,disabled}:{label:string;values:string[];onChange:(v:string[])=>void;image:boolean;disabled?:boolean}){
  const {ui}=useLocale(); const [uploading,setUploading]=useState(false); const upload=async(files:FileList|null)=>{if(!files)return;setUploading(true);try{const added:string[]=[];for(const file of Array.from(files)){const fd=new FormData();fd.append('file',file);const {data}=await api.post<{path:string}>(`/uploads/${image?'portal-image':'portal-file'}`,fd);added.push(data.path);}onChange([...values,...added]);}catch(e){toast.error(apiError(e));}finally{setUploading(false);}};
  return <div className="space-y-2 md:col-span-2"><Label>{label}</Label>{!disabled&&<label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed p-4 text-sm text-muted-foreground hover:border-primary"><Upload className="size-4"/>{ui(uploading?'جاري الرفع...':'اختر ملفًا أو أكثر')}<input className="hidden" type="file" multiple accept={image?'image/*':undefined} disabled={uploading} onChange={e=>void upload(e.target.files)}/></label>}<div className="flex flex-wrap gap-2">{values.map((v,i)=><span key={`${v}-${i}`} className="inline-flex max-w-full items-center gap-2 rounded-md bg-muted px-2 py-1 text-xs"><a className="max-w-72 truncate text-primary" href={v.startsWith('http')?v:`/uploads/${v}`} target="_blank" rel="noreferrer">{v.split('/').pop()}</a>{!disabled&&<button type="button" aria-label={ui('إزالة الملف')} onClick={()=>onChange(values.filter((_,x)=>x!==i))}><X className="size-3"/></button>}</span>)}</div></div>;
}

function displayValue(row:Row,field:Field,options:Options|undefined,ui:(text:string)=>string){const v=field.key==='title'?row.title:field.key==='branchId'?row.branchId:row.data[field.key];if(field.type==='branch')return options?.branches.find(x=>x.id===Number(v))?.name??row.data.branchName??(row.data.legacy_branch_id?`${ui('غير معيّن')} (${ui('رقم الفرع القديم')} ${row.data.legacy_branch_id})`:'—');if(field.type==='employee')return options?.employees.find(x=>x.id===Number(v))?.name??row.data.captainName??(row.data.legacy_captain_id?`${ui('غير معيّن')} (${ui('رقم الموظف القديم')} ${row.data.legacy_captain_id})`:'—');if(field.type==='category')return row.data.categoryName??'—';if(typeof v==='boolean'||v===0||v===1)return ui(v?'نعم':'لا');return clean(v)||'—';}
function statusLabel(v:string){return ({active:'نشط',inactive:'موقوف',notactive:'موقوف',unread:'غير مقروءة',read:'مقروءة',pending:'قيد الانتظار',accepted:'مقبول',rejected:'مرفوض',processing:'قيد المعالجة',completed:'مكتمل',cancelled:'ملغي'} as Record<string,string>)[v]??v;}

function CaptainReport({config}:{config:Config}){
  const {ui,locale}=useLocale(); const optionsQuery=useOptions(); const options=optionsQuery.data; const [from,setFrom]=useState('');const [to,setTo]=useState('');const [captainId,setCaptainId]=useState('all'); const numberLocale=locale==='ar'?'ar-EG':'en-US';
  const {data=[],isLoading,isError,error,refetch}=useQuery({queryKey:['portal-captain-report',from,to,captainId],queryFn:async()=>(await api.get<Array<Record<string,any>>>('/portal-management/reports/captain-sales',{params:{from:from||undefined,to:to||undefined,captainId:captainId==='all'?undefined:captainId}})).data});
  if(isError)return <ErrorState message={apiError(error)} onRetry={()=>void refetch()}/>;
  if(optionsQuery.isError)return <ErrorState message={apiError(optionsQuery.error)} onRetry={()=>void optionsQuery.refetch()}/>;
  const totals=data.reduce((a,r)=>({orders:a.orders+Number(r.orderCount),gross:a.gross+Number(r.grossTotal),discount:a.discount+Number(r.discountTotal),net:a.net+Number(r.netTotal)}),{orders:0,gross:0,discount:0,net:0});
  return <div className="space-y-6"><PageHeader title={ui(config.title)} eyebrow={ui('إدارة البوابة')}/><Card><CardContent className="grid gap-4 p-5 md:grid-cols-3"><div><Label id="portal-field-3">{ui('من تاريخ')}</Label><Input aria-labelledby="portal-field-3" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><Label id="portal-field-4">{ui('إلى تاريخ')}</Label><Input aria-labelledby="portal-field-4" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div><Label id="portal-field-5">{ui('الكابتن')}</Label><Select value={captainId} onValueChange={setCaptainId}><SelectTrigger aria-labelledby="portal-field-5"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{ui('كل الكباتن')}</SelectItem>{options?.employees.map(e=><SelectItem key={e.id} value={String(e.id)}>{e.name}</SelectItem>)}</SelectContent></Select></div></CardContent></Card><div className="grid gap-3 md:grid-cols-4">{[['عدد الطلبات',totals.orders],['إجمالي قبل الخصم',totals.gross],['الخصومات',totals.discount],['صافي المبيعات',totals.net]].map(([l,v])=><Card key={String(l)}><CardContent className="p-5"><div className="text-sm text-muted-foreground">{ui(String(l))}</div><div className="mt-2 text-2xl font-bold">{Number(v).toLocaleString(numberLocale)}</div></CardContent></Card>)}</div><Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-start">{ui('الكابتن')}</th><th className="p-3 text-start">{ui('الكود')}</th><th className="p-3">{ui('الطلبات')}</th><th className="p-3">{ui('قبل الخصم')}</th><th className="p-3">{ui('الخصم')}</th><th className="p-3">{ui('الصافي')}</th><th className="p-3">{ui('أول طلب')}</th><th className="p-3">{ui('آخر طلب')}</th></tr></thead><tbody>{isLoading?<tr><td colSpan={8} className="p-8 text-center">{ui('جاري التحميل...')}</td></tr>:!data.length?<tr><td colSpan={8} className="p-8 text-center">{ui('لا توجد مبيعات مكتملة بكود خصم في الفترة المحددة')}</td></tr>:data.map((r,i)=><tr key={`${r.captainId}-${r.discountCode}-${i}`} className="border-b"><td className="p-3">{r.captain??'—'}</td><td className="p-3">{r.discountCode}</td><td className="p-3 text-center">{r.orderCount}</td><td className="p-3 text-center">{Number(r.grossTotal).toLocaleString(numberLocale)}</td><td className="p-3 text-center">{Number(r.discountTotal).toLocaleString(numberLocale)}</td><td className="p-3 text-center font-semibold">{Number(r.netTotal).toLocaleString(numberLocale)}</td><td className="p-3 text-center">{clean(r.firstOrder).slice(0,10)}</td><td className="p-3 text-center">{clean(r.lastOrder).slice(0,10)}</td></tr>)}</tbody></table></CardContent></Card></div>;
}
