import { Prisma } from '@prisma/client';
import { EXPENSE_APPROVED, nextFinDocNumber } from './finance.utils';

/**
 * Mirror an expense generated by another module into the operational expense register.
 * The caller posts the GL itself; this row is display/audit data and must never post a second GL entry.
 */
export async function recordSystemExpense(
  tx: Prisma.TransactionClient,
  input: {
    invoiceNumber: string;
    date: string;
    category: string;
    subCategory?: string;
    amount: number;
    description: string;
    vendor?: string;
    branchId?: number;
    createdBy?: number;
    paymentMethod?: string;
  },
) {
  const amount = Math.round(input.amount * 100) / 100;
  if (amount <= 0) return;
  const existing = await tx.fin_expenses.findFirst({
    where: { invoice_number: input.invoiceNumber, is_deleted: false },
    select: { id: true },
  });
  if (existing) return;
  const expenseNumber = await nextFinDocNumber(tx, 'fin_expenses', 'expense_number', 'EXP');
  await tx.fin_expenses.create({
    data: {
      expense_number: expenseNumber,
      expense_date: input.date,
      category: input.category,
      sub_category: input.subCategory ?? null,
      amount,
      tax_amount: 0,
      total_amount: amount,
      payment_method: input.paymentMethod ?? 'نقدي',
      payment_status: 'مدفوع',
      approval_status: EXPENSE_APPROVED,
      approved_by: input.createdBy ?? null,
      approved_at: new Date(),
      description: input.description,
      vendor: input.vendor ?? null,
      invoice_number: input.invoiceNumber,
      branch_id: input.branchId ?? null,
      created_by: input.createdBy ?? null,
      notes: 'مستند تلقائي مربوط بالنظام',
    },
  });
}

/** Keep the display-only finance register aligned when its authoritative module document is reversed. */
export async function reverseSystemExpense(
  tx: Prisma.TransactionClient,
  invoiceNumber: string,
  reason: string,
) {
  const expense = await tx.fin_expenses.findFirst({
    where: { invoice_number: invoiceNumber, is_deleted: false },
    select: { id: true, notes: true },
  });
  if (!expense) return;
  await tx.fin_expenses.update({
    where: { id: expense.id },
    data: {
      is_deleted: true,
      deleted_at: new Date(),
      notes: [expense.notes, `عكس تلقائي: ${reason}`].filter(Boolean).join('\n'),
    },
  });
}
