import { Prisma } from '@prisma/client';
import {
  mapPaymentMethodToArabic,
  nextFinDocNumber,
  REVENUE_PAID,
} from './finance.utils';

/**
 * Mirror revenue generated by another module into the operational revenue register.
 * The module itself owns the GL entry; this row is for finance reports and audit only.
 */
export async function recordSystemRevenue(
  tx: Prisma.TransactionClient,
  input: {
    sourceModule: string;
    sourceRef: string;
    date: string;
    source: string;
    subSource?: string;
    amount: number;
    description?: string;
    customerName?: string;
    invoiceNumber?: string;
    branchId?: number;
    createdBy?: number;
    paymentMethod?: string;
  },
) {
  const amount = Math.round(input.amount * 100) / 100;
  if (amount === 0) return;
  const existing = await tx.fin_revenues.findFirst({
    where: {
      source_module: input.sourceModule,
      source_ref: input.sourceRef,
      is_deleted: false,
    },
    select: { id: true },
  });
  if (existing) return;

  const revenueNumber = await nextFinDocNumber(tx, 'fin_revenues', 'revenue_number', 'REV');
  await tx.fin_revenues.create({
    data: {
      revenue_number: revenueNumber,
      revenue_date: input.date,
      source: input.source,
      sub_source: input.subSource ?? null,
      amount,
      tax_amount: 0,
      discount_amount: 0,
      total_amount: amount,
      net_amount: amount,
      payment_method: mapPaymentMethodToArabic(input.paymentMethod),
      payment_status: REVENUE_PAID,
      description: input.description ?? null,
      customer_name: input.customerName ?? null,
      invoice_number: input.invoiceNumber ?? null,
      source_module: input.sourceModule,
      source_ref: input.sourceRef,
      branch_id: input.branchId ?? null,
      created_by: input.createdBy ?? null,
      notes: 'مستند تلقائي مربوط بالنظام',
    },
  });
}
