import { AccountType } from '@prisma/client';
import { SeedAccountDef } from './accounts.seed';

/** Full gym-specific chart of accounts (~90 accounts) — superset of DEFAULT_CHART. */
export const FULL_GYM_CHART: SeedAccountDef[] = [
  // ── 1 الأصول ──
  { code: '1', name: 'الأصول', accountType: 'asset', isPostable: false },
  { code: '1.01', name: 'الأصول المتداولة', accountType: 'asset', parentCode: '1', isPostable: false },
  { code: '1.01.001', name: 'الخزينة النقدية', accountType: 'asset', parentCode: '1.01', defaultKey: 'cash' },
  { code: '1.01.002', name: 'البنك', accountType: 'asset', parentCode: '1.01', defaultKey: 'bank' },
  { code: '1.01.003', name: 'بطاقات ائتمان', accountType: 'asset', parentCode: '1.01', defaultKey: 'card' },
  { code: '1.01.004', name: 'المدفوعات الإلكترونية', accountType: 'asset', parentCode: '1.01', defaultKey: 'online' },
  { code: '1.01.005', name: 'المخزون', accountType: 'asset', parentCode: '1.01', defaultKey: 'inventory' },
  { code: '1.01.006', name: 'تسوية استلام البضائع', accountType: 'asset', parentCode: '1.01', defaultKey: 'grn_clearing' },
  { code: '1.01.007', name: 'ضريبة القيمة المضافة - مدخلات', accountType: 'asset', parentCode: '1.01', defaultKey: 'vat_input' },
  { code: '1.01.008', name: 'العملاء / المدينون', accountType: 'asset', parentCode: '1.01', defaultKey: 'accounts_receivable' },
  { code: '1.01.009', name: 'سلف الموظفين', accountType: 'asset', parentCode: '1.01', defaultKey: 'employee_advances' },
  { code: '1.01.010', name: 'مصروفات مدفوعة مقدماً', accountType: 'asset', parentCode: '1.01' },
  { code: '1.02', name: 'الأصول غير المتداولة', accountType: 'asset', parentCode: '1', isPostable: false },
  { code: '1.02.001', name: 'الأراضي', accountType: 'asset', parentCode: '1.02' },
  { code: '1.02.002', name: 'المباني', accountType: 'asset', parentCode: '1.02' },
  { code: '1.02.003', name: 'أجهزة الجيم - كارديو', accountType: 'asset', parentCode: '1.02', category: 'معدات' },
  { code: '1.02.004', name: 'أجهزة الجيم - حديد', accountType: 'asset', parentCode: '1.02', category: 'معدات' },
  { code: '1.02.005', name: 'الأثاث والتجهيزات', accountType: 'asset', parentCode: '1.02' },
  { code: '1.02.006', name: 'السيارات', accountType: 'asset', parentCode: '1.02' },
  { code: '1.02.007', name: 'تحسينات المباني', accountType: 'asset', parentCode: '1.02' },
  { code: '1.02.008', name: 'مجمع الإهلاك', accountType: 'asset', parentCode: '1.02', defaultKey: 'accumulated_depreciation' },
  { code: '1.03', name: 'الأصول غير الملموسة', accountType: 'asset', parentCode: '1', isPostable: false },
  { code: '1.03.001', name: 'برمجيات وتراخيص', accountType: 'asset', parentCode: '1.03' },
  { code: '1.03.002', name: 'الشهرة', accountType: 'asset', parentCode: '1.03' },

  // ── 2 الخصوم ──
  { code: '2', name: 'الخصوم', accountType: 'liability', isPostable: false },
  { code: '2.01', name: 'الخصوم المتداولة', accountType: 'liability', parentCode: '2', isPostable: false },
  { code: '2.01.001', name: 'الدائنون / الموردون', accountType: 'liability', parentCode: '2.01', defaultKey: 'accounts_payable' },
  { code: '2.01.002', name: 'ضريبة القيمة المضافة - مخرجات', accountType: 'liability', parentCode: '2.01', defaultKey: 'vat_output' },
  { code: '2.01.003', name: 'رواتب مستحقة', accountType: 'liability', parentCode: '2.01', defaultKey: 'salaries_payable' },
  { code: '2.01.004', name: 'اشتراكات محصلة مقدماً', accountType: 'liability', parentCode: '2.01', defaultKey: 'deferred_revenue' },
  { code: '2.01.005', name: 'ضرائب مستحقة', accountType: 'liability', parentCode: '2.01' },
  { code: '2.01.006', name: 'تأمينات اجتماعية مستحقة', accountType: 'liability', parentCode: '2.01', defaultKey: 'social_insurance_payable' },
  { code: '2.01.007', name: 'تسويات الشركاء المستحقة', accountType: 'liability', parentCode: '2.01', defaultKey: 'partner_payable' },
  { code: '2.02', name: 'الخصوم غير المتداولة', accountType: 'liability', parentCode: '2', isPostable: false },
  { code: '2.02.001', name: 'قروض طويلة الأجل', accountType: 'liability', parentCode: '2.02' },

  // ── 3 حقوق الملكية ──
  { code: '3', name: 'حقوق الملكية', accountType: 'equity', isPostable: false },
  { code: '3.01', name: 'رأس المال', accountType: 'equity', parentCode: '3', defaultKey: 'opening_balance_equity' },
  { code: '3.02', name: 'الأرباح المحتجزة', accountType: 'equity', parentCode: '3' },
  { code: '3.03', name: 'الأرباح / الخسائر الحالية', accountType: 'equity', parentCode: '3' },
  { code: '3.04', name: 'احتياطي نظامي', accountType: 'equity', parentCode: '3' },
  { code: '3.05', name: 'احتياطي اختياري', accountType: 'equity', parentCode: '3' },

  // ── 4 الإيرادات ──
  { code: '4', name: 'الإيرادات', accountType: 'revenue', isPostable: false },
  { code: '4.01', name: 'إيرادات التشغيل', accountType: 'revenue', parentCode: '4', isPostable: false },
  { code: '4.01.001', name: 'إيرادات الاشتراكات', accountType: 'revenue', parentCode: '4.01', defaultKey: 'subscription_revenue' },
  { code: '4.01.002', name: 'إيرادات المبيعات', accountType: 'revenue', parentCode: '4.01', defaultKey: 'sales_revenue' },
  { code: '4.01.003', name: 'إيرادات التدريب الشخصي', accountType: 'revenue', parentCode: '4.01' },
  { code: '4.01.004', name: 'إيرادات التدريب الجماعي', accountType: 'revenue', parentCode: '4.01' },
  { code: '4.01.005', name: 'إيرادات التدريب أونلاين', accountType: 'revenue', parentCode: '4.01' },
  { code: '4.01.006', name: 'إيرادات الخدمات الإضافية', accountType: 'revenue', parentCode: '4.01' },
  { code: '4.01.007', name: 'إيرادات المكملات الغذائية', accountType: 'revenue', parentCode: '4.01' },
  { code: '4.01.008', name: 'إيرادات الملابس الرياضية', accountType: 'revenue', parentCode: '4.01' },
  { code: '4.01.009', name: 'إيرادات الخزائن', accountType: 'revenue', parentCode: '4.01' },
  { code: '4.01.010', name: 'إيرادات السبا', accountType: 'revenue', parentCode: '4.01' },
  { code: '4.01.011', name: 'إيرادات InBody', accountType: 'revenue', parentCode: '4.01' },
  { code: '4.02', name: 'إيرادات غير التشغيل', accountType: 'revenue', parentCode: '4', isPostable: false },
  { code: '4.02.001', name: 'إيرادات فوائد', accountType: 'revenue', parentCode: '4.02' },
  { code: '4.02.002', name: 'أرباح بيع أصول', accountType: 'revenue', parentCode: '4.02' },
  { code: '4.02.003', name: 'إيرادات أخرى', accountType: 'revenue', parentCode: '4.02', defaultKey: 'other_revenue' },
  { code: '4.03', name: 'خصومات الاشتراكات', accountType: 'revenue', parentCode: '4', defaultKey: 'subscription_discount' },
  { code: '4.04', name: 'خصومات المبيعات', accountType: 'revenue', parentCode: '4', defaultKey: 'sales_discount' },
  { code: '4.05', name: 'خصومات المشتريات', accountType: 'revenue', parentCode: '4', defaultKey: 'purchase_discount' },

  // ── 5 المصروفات ──
  { code: '5', name: 'المصروفات', accountType: 'expense', isPostable: false },
  { code: '5.01', name: 'مصروفات التشغيل', accountType: 'expense', parentCode: '5', isPostable: false },
  { code: '5.01.001', name: 'مصروفات عامة', accountType: 'expense', parentCode: '5.01', defaultKey: 'operating_expense' },
  { code: '5.01.002', name: 'غرامات التأخير', accountType: 'expense', parentCode: '5.01', defaultKey: 'late_fee_expense' },
  { code: '5.01.003', name: 'إيجار', accountType: 'expense', parentCode: '5.01', category: 'تشغيل' },
  { code: '5.01.004', name: 'صيانة أجهزة الجيم', accountType: 'expense', parentCode: '5.01', category: 'تشغيل', defaultKey: 'maintenance_expense' },
  { code: '5.01.005', name: 'رواتب المدربين', accountType: 'expense', parentCode: '5.01', category: 'رواتب' },
  { code: '5.01.006', name: 'رواتب الإداريين', accountType: 'expense', parentCode: '5.01', category: 'رواتب' },
  { code: '5.01.007', name: 'تسويق وإعلان', accountType: 'expense', parentCode: '5.01', category: 'تسويق' },
  { code: '5.01.008', name: 'مرافق (كهرباء/ماء)', accountType: 'expense', parentCode: '5.01', category: 'تشغيل' },
  { code: '5.01.009', name: 'تأمين', accountType: 'expense', parentCode: '5.01', category: 'تشغيل' },
  { code: '5.01.010', name: 'مستلزمات نظافة', accountType: 'expense', parentCode: '5.01', category: 'تشغيل' },
  { code: '5.01.011', name: 'مصروف الرواتب والأجور', accountType: 'expense', parentCode: '5.01', category: 'رواتب', defaultKey: 'salary_expense' },
  { code: '5.01.012', name: 'عمولات وأتعاب المدربين', accountType: 'expense', parentCode: '5.01', category: 'رواتب', defaultKey: 'trainer_commission_expense' },
  { code: '5.02', name: 'مصروفات إدارية وعمومية', accountType: 'expense', parentCode: '5', isPostable: false },
  { code: '5.02.001', name: 'قرطاسية ومكتب', accountType: 'expense', parentCode: '5.02' },
  { code: '5.02.002', name: 'اتصالات وإنترنت', accountType: 'expense', parentCode: '5.02' },
  { code: '5.02.003', name: 'ضيافة', accountType: 'expense', parentCode: '5.02' },
  { code: '5.03', name: 'مصروفات مالية وضريبية', accountType: 'expense', parentCode: '5', isPostable: false },
  { code: '5.03.001', name: 'فوائد قروض', accountType: 'expense', parentCode: '5.03' },
  { code: '5.03.002', name: 'عمولات بنكية', accountType: 'expense', parentCode: '5.03' },
  { code: '5.03.003', name: 'ضريبة الدخل', accountType: 'expense', parentCode: '5.03' },
  { code: '5.04', name: 'الإهلاك', accountType: 'expense', parentCode: '5', isPostable: false },
  { code: '5.04.001', name: 'إهلاك المباني', accountType: 'expense', parentCode: '5.04' },
  { code: '5.04.002', name: 'إهلاك أجهزة الجيم', accountType: 'expense', parentCode: '5.04' },
  { code: '5.05', name: 'خسائر أصول', accountType: 'expense', parentCode: '5' },
  { code: '5.06', name: 'فروق عملة', accountType: 'expense', parentCode: '5' },
  { code: '5.07', name: 'مصروفات غير متكررة', accountType: 'expense', parentCode: '5' },
  { code: '5.08', name: 'تكلفة البضاعة المباعة', accountType: 'expense', parentCode: '5', defaultKey: 'cost_of_goods_sold' },
];

export const FULL_GYM_CHART_COUNT = FULL_GYM_CHART.length;
