/**
 * Gym sales module routes — mirrors SwatGym sidebar under `/inventory`, `/procurement`, `/sales`.
 */
export const GYM_SALES_ROUTES = {
  inventory: {
    dashboard: '/inventory/dashboard',
    settings: '/inventory/settings',
    products: '/inventory/products',
    priceList: '/inventory/price-list',
    openingStock: '/inventory/opening-stock',
    transactions: '/inventory/transactions',
    movementLog: '/inventory/movement-log',
    stockTaking: '/inventory/stock-taking',
    policies: '/inventory/policies',
    analytics: '/inventory/analytics',
    gymIssue: '/inventory/gym-issue',
    root: '/inventory',
  },
  cafe: {
    root: '/club/cafe',
    products: '/club/cafe/products',
    categories: '/club/cafe/categories',
    rawMaterials: '/club/cafe/raw-materials',
    reports: '/club/cafe/reports',
    feedbackReports: '/club/cafe/reports/feedback',
    purchases: '/club/cafe/purchases',
    suppliers: '/club/cafe/suppliers',
    stockTaking: '/club/cafe/stock-taking',
    movements: '/club/cafe/movements',
    pos: '/sales/new',
  },
  procurement: {
    root: '/procurement',
    settings: '/procurement/settings',
    requisitions: '/procurement/requisitions',
    purchaseOrders: '/procurement/purchase-orders',
    quickPo: '/procurement/quick-po',
    goodsReceipts: '/procurement/goods-receipts',
    invoices: '/procurement/invoices',
    returns: '/procurement/returns',
    returnsDebit: '/procurement/returns-debit',
    dashboard: '/procurement/dashboard',
  },
  sales: {
    root: '/sales',
    newReceipt: '/sales/new',
    drafts: '/sales/drafts',
    invoices: '/sales/invoices',
    shifts: '/sales/shifts',
    revenue: '/sales/revenue',
    treasury: '/sales/treasury',
    settlements: '/sales/settlements',
    posAdmin: '/sales/pos-admin',
    bookings: '/sales/bookings',
  },
} as const;
