import {
  Activity,
  AlertTriangle,
  Archive,
  Banknote,
  Bell,
  Briefcase,
  Building2,
  CalendarDays,
  CalendarRange,
  ChartBar,
  CheckCircle2,
  ClipboardList,
  Clock,
  Cog,
  CreditCard,
  FileText,
  Fingerprint,
  FolderOpen,
  Gauge,
  GraduationCap,
  HandCoins,
  IdCard,
  LayoutDashboard,
  ListChecks,
  type LucideIcon,
  MapPin,
  Megaphone,
  Network,
  Plane,
  Settings2,
  ShieldCheck,
  Star,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  XCircle,
} from 'lucide-react';

/** Maps legacy FontAwesome `pages.page_icon_code` values to lucide icons. */
const MAP: Record<string, LucideIcon> = {
  'tachometer-alt': LayoutDashboard,
  tachometer: LayoutDashboard,
  gauge: Gauge,
  users: Users,
  user: Users,
  'user-plus': UserPlus,
  'user-cog': UserCog,
  'user-secret': ShieldCheck,
  'user-times': XCircle,
  'id-card': IdCard,
  'id-badge': IdCard,
  fingerprint: Fingerprint,
  clock: Clock,
  calendar: CalendarDays,
  'calendar-alt': CalendarRange,
  'calendar-check': CalendarDays,
  'calendar-day': CalendarDays,
  'money-bill': Banknote,
  'money-bill-alt': Banknote,
  'money-check': CreditCard,
  'hand-holding-usd': HandCoins,
  wallet: Wallet,
  coins: HandCoins,
  cog: Settings2,
  cogs: Cog,
  'chart-bar': ChartBar,
  'chart-line': Activity,
  'chart-pie': ChartBar,
  file: FileText,
  'file-alt': FileText,
  'file-invoice': FileText,
  list: ListChecks,
  'list-ul': ListChecks,
  'clipboard-list': ClipboardList,
  building: Building2,
  sitemap: Network,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  bell: Bell,
  bullhorn: Megaphone,
  'map-marker-alt': MapPin,
  'map-marker': MapPin,
  plane: Plane,
  star: Star,
  exclamation: AlertTriangle,
  'exclamation-triangle': AlertTriangle,
  check: CheckCircle2,
  close: XCircle,
  times: XCircle,
  ring: Star,
  archive: Archive,
  'folder-open': FolderOpen,
  book: FileText,
};

export function iconFor(code: string | null | undefined): LucideIcon {
  if (!code) return ListChecks;
  const match = code.match(/fa[srb]?\s+fa-([a-z0-9-]+)|fa-([a-z0-9-]+)/i);
  const key = match?.[1] ?? match?.[2];
  return (key && MAP[key]) || ListChecks;
}
